version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/moodledata
    depends_on:
      - db
    entrypoint: ["sh", "-c", "service cron start && apache2-foreground"]

  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: ShiHi9si
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: